### PR TITLE
Fix deletion of wrong assets in multisite setup

### LINKED ISSUE #1138: The plugin erroneously deletes pages
## Bug Description

The plugin sometimes deletes non-attachment posts.

## Expected Behaviour

The plugin should not delete anything other than its own settings.

## Steps to reproduce

I am not sure of the exact steps to reproduce. I know the lines that create the bug, but not the reason for them:

Inside `php/class-assets.php` there are these lines:

    // Get the disabled items. 
    foreach ( $this->asset_parents as $url => $parent ) {
      if ( isset( $this->active_parents[ $url ] ) ) { continue; }
      $this->purge_parent( $parent->ID ); // Remove parent.
      wp_delete_post( $parent->ID ); 
    }

This happens on a WordPress multisite. 

This is my total guess of what is going on:

1. The plugin has a queue of tasks, including post IDs and actions
2. The multisite switches site to a different site to the one the plugin was created on
3. The queue processes an action, based on an ID of a resource from a different multisite
4. Chaos ensues.

## Additional context

To identify the affiliation with the Cloudinary plugin, I created the following plugin:

    <?php
    /**
     * MU plugin: log who trashes the homepage.
     */
    add_action('wp_trash_post', function ($post_id) {
        if ((int) $post_id !== 5361) return;
    
        error_log("🔥 Homepage trashed (post_id=5361) on blog_id=" . get_current_blog_id());
        error_log("Request URI: " . ($_SERVER['REQUEST_URI'] ?? ''));
        error_log("User: " . (get_current_user_id() ?: 0));
    
        // Backtrace without args (less noisy)
        $trace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);
       foreach ($trace as $i => $t) {
            $file = $t['file'] ?? '';
            $line = $t['line'] ?? '';
            $func = $t['function'] ?? '';
            $class = $t['class'] ?? '';
            $type = $t['type'] ?? '';
            error_log(sprintf("#%d %s:%s %s%s%s()", $i, $file, $line, $class, $type, $func));
            if ($i >= 25) break; // keep logs sane
        }
    }, 10, 1);

Which outputs:

    [Wed Feb 04 16:25:09.686469 2026] [proxy_fcgi:error] [pid 872:tid 127594997434048] 
    AH01071: Got error 'PHP message:  Homepage trashed (post_id=5361) on blog_id=1PHP message:
    Request URI: /wp-json/cloudinary/v1/queuePHP message:
    User: 1
    PHP message: #0 /home/storm/sites/website/public/wp-includes/class-wp-hook.php:326 {closure}()
    PHP message: #1 /home/storm/sites/website/public/wp-includes/class-wp-hook.php:348 WP_Hook->apply_filters()
    PHP message: #2 /home/storm/sites/website/public/wp-includes/plugin.php:517 WP_Hook->do_action()
    PHP message: #3 /home/storm/sites/website/public/wp-includes/post.php:3757 do_action()
    PHP message: #4 /home/storm/sites/website/public/wp-includes/post.php:3502 wp_trash_post()
    PHP message: #5 /home/storm/sites/website/public/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-assets.php:505 wp_delete_post()
    PHP message: #6 /home/storm/sites/website/public/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-assets.php:1296 Cloudinary\\Assets->activate_parents()
    PHP message: #7 /home/storm/sites/website/public/wp-includes/class-wp-hook.php:324 Cloudinary\\Assets->setup()
    PHP message: #8 /home/storm/sites/website/public/wp-includes/class-wp-hook.php:348 WP_Hook->apply_filters()
    PHP message: #9 /home/storm/sites/website/public/wp-includes/plugin.php:517 WP_Hook->do_action()
    PHP message: #10 /home/storm/sites/website/public/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-plugin.php:467 do_action()
    PHP message: #11 /home/storm/sites/website/public/wp-includes/class-wp-hook.php:324 Cloudinary\\Plugin->setup()
    PHP message: #12 /home/storm/sites/website/public/wp-includes/class-wp-hook.php:348 WP_Hook->apply_filters()
    PHP message: #13 /home/storm/sites/website/public/wp-includes/plugin.php:517 WP_Hook->do_action()
    PHP message: #14 /home/storm/sites/website/public/wp-settings.php:700 do_action()
    PHP message: #15 /home/storm/sites/website/public/wp-config.php:102 require_once()
    PHP message: #16 /home/storm/sites/website/public/wp-load.php:50 require_once()
    PHP message: #17 /home/storm/sites/website/public/wp-blog-header.php:13 require_once()
    PHP message: #18 /home/storm/sites/website/public/index.php:17 require()'

### PR DESCRIPTION
**Pull request by gabrielcld2**
<!-- Please reference the issue number this pull request addresses. -->
Fixes #1138 

## Context 

This bug is related to non-media assets such as Theme files, plugin files, WP core files, and upload-dir content. 

### The issue                                                                                                                                                                                                                
  In a WordPress Multisite, PHP can switch blog contexts within the same process via switch_to_blog() — this happens during cron, AJAX handlers, WooCommerce, WPML, and other plugins.
If the switch happen during the assets purging process, current Cloudinary plugin might delete assets from the wrong site.
         
#### The scenario 

1. The singleton Assets instance loads with Site B's parent posts in $this->asset_parents (loaded during init_asset_parents()), now stamped with blog_id = 2.
2. Something (cron, another plugin) switches the context back to Site A (blog_id = 1).                                                                                                                                            
3. activate_parents() runs in Site A's context: get_current_blog_id() returns 1.      
4. Site B's parents are NOT in Site A's $this->active_parents (Site A has different configured paths).                                                                                                                            
   1. Without the fix: Site B's parents — and all their child assets — get purged. Asset posts deleted, Cloudinary sync records cleared.                                                                                             
   2. With the fix: The $parent->blog_id !== $blog_id guard skips them.                                                                                                                                                              
                                                                                                                                                                                                                          
### What the Fix Does                                                                                                                                                                                                                 
          
1. add_asset_parent() method stamps each parent post object with blog_id = get_current_blog_id() when running on a multisite, at the moment of loading/creation. This happens in both init_asset_parents() and                    
  create_asset_parent().
2. Guard in activate_parents() — before calling purge_parent() + wp_delete_post() on an inactive parent, it now checks: if $parent->blog_id is set and doesn't match the current blog ID, skip it.                                
                                                                                                                                                                                                                                    

## QA Notes

### Prerequisites

  - WordPress Multisite with at least 2 active subsites (Site A and Site B).                                                                                                                                                        
  - Cloudinary plugin network-activated (or manually activated on both sites).
  - Cloudinary credentials connected and configured on both sites (same or separate accounts).                                                                                                                                      
  - WP-CLI & SQL client access for reliable reproduction and testing                                                                                                                                                              
                                                                                                                                                                                                   
### Setup Phase
  
  On Site B:

  1. Go to Cloudinary → Connect → scroll to Additional Asset Sync Settings.                                                                                                                                                         
  2. Enable asset syncing and toggle ON at least one asset group — e.g., Themes or Plugins.
  3. Save settings.                                                                                                                                                                                                                 
  4. Visit a Site B frontend page (any page) to trigger asset discovery.                                                                                                                                                            
  5. Return to Site B's Cloudinary admin — this triggers activate_parents() and creates the parent posts.
  
                                                                                                                                                                                                      
### Record the baseline (DB check) 

(Note: Replace `wp_3_` with your Site B's table prefix if different):

```sql  
SELECT ID, post_title, post_type, post_status                                                                                                                                                                                     
  FROM wp_3_posts                                                                                                                                                                                                                   
  WHERE post_type = 'cloudinary_asset' AND post_parent = 0;
```                                                                                                                                                                                                                          
Note the IDs and count of Site B's asset parents.

### Reproducing the issue

Reproducing the Cross-Blog Scenario (Reliable Method via WP-CLI)

Run the following the command via WP CLI (make sure to replace the URL param to point to your site A, and site B's ID in the switch_to_blog call within the script if needed):
```shell
wp --url=cloudinary-multisite.local/site-1/ eval '
$plugin = Cloudinary\get_plugin_instance();
$assets = $plugin->get_component( "assets" );
switch_to_blog( 3 );

$r = new ReflectionClass( $assets );
$m = $r->getMethod( "init_asset_parents" );
$m->setAccessible( true );
$m->invoke( $assets );

restore_current_blog();

$m2 = $r->getMethod( "activate_parents" );
$m2->setAccessible( true );
$m2->invoke( $assets );'
```

This script basically emulates what a cron or plugin might do which is to trigger the assets parents purge across both sites while switching to another blog.

### Verify
                                                                           
After running, re-check the DB:                                                                                                                                                                                                   
`SELECT COUNT(*) FROM wp_3_posts WHERE post_type = 'cloudinary_asset' AND post_parent = 0;`

Expected with the fix: Count is unchanged. Site B's parents survive and didn't get deleted.
  
### Testing Normal Purge Still Works (Regression)                                                                                                           
To ensure the fix doesn't break the legitimate purge behavior:

1. On Site A, enable Plugins asset sync and save → verify plugin parents are created.
2. On Site A, disable Plugins asset sync and save → verify Site A's plugin parents and their children are deleted.
3. Site B's assets should still be unaffected throughout.

### CODE REVIEW

File: php/class-assets.php [hunk 1]
```diff
@@ -1773,4 +1782,19 @@ protected function add_external_settings() {
...
+	/**
+	 * Assign a parent asset to the asset parents array.
+	 * If this is a multisite installation, also assign the current blog ID to the post object for later checks.
+	 *
+	 * @param \WP_Post $post The post to assign.
+	 * @return void
+	 */
+	protected function add_asset_parent( $post ) {
+		if ( is_multisite() ) {
+			$post->blog_id = get_current_blog_id();
```
Comment (PatelUtkarsh) [inline php/class-assets.php:1795]: **💡 thought:** Stamping blog_id as a dynamic property on WP_Post only works because WP core annotated WP_Post with `#[AllowDynamicProperties]` (WP 6.4+). On sites running PHP 8.2+ with older WordPress, this triggers deprecation warnings. Which is odd combo anyway.

**Review by PatelUtkarsh — APPROVED** [review]
Looks good!

File: php/class-assets.php (hunk 1 above)
Comment (gabrielcld2) [reply php/class-assets.php:1795]: Good point! It's probably fine if it's just a deprecation warning given the odd combination of WP & PHP version like you said, it's quite unlikely to happen.
